apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: nginx-route3
  namespace: default
spec:
  hostnames:
    - app1.int.winning.wtf
  parentRefs:
    - name: eg    # same Gateway as before
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: nginx3
          port: 80
