apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: pgadmin
  namespace: database
spec:
  parentRefs:
    - name: eg
      namespace: default
  hostnames:
    - db.winning.wtf
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /pgadmin
      backendRefs:
        - name: pgadmin-pgadmin4    # matches Helm release service name
          port: 80
