apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pgadmin-credentials
  namespace: database
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-cluster-secretsmanager
  target:
    name: pgadmin-credentials
    creationPolicy: Owner
  data:
    - secretKey: pgadmin-password
      remoteRef:
        key: pgadmin-password
    - secretKey: app-user-password
      remoteRef:
        key: app-user-password
