apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pgadmin-credentials
  namespace: database
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-cluster-secretsmanager
  target:
    name: pgadmin-credentials
    creationPolicy: Owner
  data:
    - secretKey: password              # <- pgAdmin expects this
      remoteRef:
        key: pgadmin-password          # Bitwarden secret name
    - secretKey: email                 # optional
      remoteRef:
        key: pgadmin-email             # Bitwarden secret name (optional)
