apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: it-tools-route
  namespace: default
spec:
  parentRefs:
    - name: eg
  hostnames:
    - "atools.int.winning.wtf"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: it-tools
          port: 8080
          weight: 1
