apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jellyfin-secret
  namespace: jellyfin
spec:
  secretStoreRef:
    name: bitwarden-cluster-secretsmanager
    kind: ClusterSecretStore
  refreshInterval: 5m
  target:
    name: jellyfin-secret
    creationPolicy: Owner
  data:
    - secretKey: admin-password
      remoteRef:
        key: JellyfinAdminPassword
